In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Social_Network_Ads.csv')
df.head()

In [ ]:
df.tail()

In [ ]:
df.isnull().sum()

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
sns.pairplot(df)

In [ ]:
corr_hmap=df.corr()
plt.figure(figsize=(5,6))
sns.heatmap(corr_hmap,annot=True)
plt.show()

In [ ]:
x=df.iloc[:,-2].values
x

In [ ]:
x=x.reshape(-1,1)


In [ ]:
y=df.iloc[:,-1].values

y=y.reshape(-1,1)
y

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=45)

In [39]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))

0.6136363636363636
[[54  0]
 [34  0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76        54
           1       0.00      0.00      0.00        34

    accuracy                           0.61        88
   macro avg       0.31      0.50      0.38        88
weighted avg       0.38      0.61      0.47        88



In [40]:
svc=SVC()
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.625
[[46  8]
 [25  9]]
              precision    recall  f1-score   support

           0       0.65      0.85      0.74        54
           1       0.53      0.26      0.35        34

    accuracy                           0.62        88
   macro avg       0.59      0.56      0.54        88
weighted avg       0.60      0.62      0.59        88



In [41]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.75
[[52  2]
 [20 14]]
              precision    recall  f1-score   support

           0       0.72      0.96      0.83        54
           1       0.88      0.41      0.56        34

    accuracy                           0.75        88
   macro avg       0.80      0.69      0.69        88
weighted avg       0.78      0.75      0.72        88



In [42]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_train,y_train)
preddt=dt.predict(x_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

0.6931818181818182
[[45  9]
 [18 16]]
              precision    recall  f1-score   support

           0       0.71      0.83      0.77        54
           1       0.64      0.47      0.54        34

    accuracy                           0.69        88
   macro avg       0.68      0.65      0.66        88
weighted avg       0.69      0.69      0.68        88



In [43]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier()
gbc.fit(x_train,y_train)
gbc.score(x_train,y_train)
predgbc=gbc.predict(x_test)
print(accuracy_score(y_test,predgbc))
print(confusion_matrix(y_test,predgbc))

print(classification_report(y_test,predgbc))

0.7045454545454546
[[45  9]
 [17 17]]
              precision    recall  f1-score   support

           0       0.73      0.83      0.78        54
           1       0.65      0.50      0.57        34

    accuracy                           0.70        88
   macro avg       0.69      0.67      0.67        88
weighted avg       0.70      0.70      0.70        88



In [44]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [45]:
kf = KFold(n_splits=5,shuffle=True, random_state=123)

In [46]:
cv_scores = cross_val_score(lr,x_train,y_train,cv=kf)
cv_scores

array([0.6984127 , 0.65079365, 0.74193548, 0.51612903, 0.64516129])

In [47]:
kf = KFold(n_splits=10,shuffle=True, random_state=123)
cv_scores = cross_val_score(lr,x_train,y_train,cv=kf)
cv_scores

array([0.75      , 0.625     , 0.58064516, 0.74193548, 0.74193548,
       0.74193548, 0.51612903, 0.51612903, 0.74193548, 0.5483871 ])

In [48]:
kf = KFold(n_splits=10,shuffle=True, random_state=123)
cv_scores = cross_val_score(gbc,x_train,y_train,cv=kf)
cv_scores

array([0.875     , 0.59375   , 0.80645161, 0.96774194, 0.80645161,
       0.74193548, 0.80645161, 0.61290323, 0.74193548, 0.67741935])

In [49]:
kf = KFold(n_splits=10,shuffle=True, random_state=123)
cv_scores = cross_val_score(gnb,x_train,y_train,cv=kf)
cv_scores

array([0.875     , 0.6875    , 0.80645161, 0.90322581, 0.80645161,
       0.80645161, 0.80645161, 0.61290323, 0.77419355, 0.70967742])

so we can see here after using cross score validation we can iprove the result of all the Algorithm
The Average Accuracy score of model is more then 80%